### PR TITLE
Real Nukkit 1.1 Fix - Try it

### PR DESCRIPTION
**Pull request by Goodstuff4UonYT**
https://github.com/yescallop/Nukkit/tree/1.1.0 (1.1 Version)

### CODE REVIEW

**Comment by EnderKenji** [comment]
@boy0001 Please review it and try fix the RIGHT_CLICK . Thanks a lot.

**Comment by Goodstuff4UonYT** [comment]
Nukkit is on version 1.1 now

**Comment by boy0001** [comment]
Why did you change the quit event?

**Comment by EnderKenji** [comment]
Jenkins build failed.

**Pull request merged**
