### PR TITLE
Replace currentTimeMillis() with nanoTime() for higher accuracy

### PR DESCRIPTION
**Pull request by hafarooki**

### CODE REVIEW

**Comment by boy0001** [comment]
The time provided is still in milliseconds, so is there any benefit to measuring it in nanoseconds here?

**Comment by Miclebrick** [comment]
currentTimeMillis is not as accurate as nanoTime, iirc it is only accurate to 15ms. I'll look into it in a bit

**Comment by Miclebrick** [comment]
https://stackoverflow.com/questions/351565/system-currenttimemillis-vs-system-nanotime

**Comment by Miclebrick** [comment]
It's the same precision used this way, but depending on the OS and Java version, significantly higher accuracy

**Comment by Miclebrick** [comment]
Also current time millis is wall time and can be affected by system time changes, time zone changes, daylight savings changes, etc, whereas nanoTime is based arbitrary starting point and meant for measuring elapsed time.

**Review by SirYwell — APPROVED** [review]

**Comment by Miclebrick** [comment]
was this forgotten? 😛

**Comment by boy0001** [comment]
yeah, kinda. On its own this doesn't really do anything since the rest of the code that calls it still uses millis.

**Comment by Miclebrick** [comment]
RIP. Better than nothing though, especially for such a critical part, right?

**Comment by boy0001** [comment]
yeah, I just need to get around to fixing the rest of it and I'll merge this.

**Comment by NotMyFault** [comment]
This repository is no longer in use. Please submit issues and feature requests on https://github.com/IntellectualSites/FastAsyncWorldEdit

**Pull request closed without merging**
